# Generated by Django 4.2.4 on 2023-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_product_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_discount",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
